/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Proizvod;
import domen.Proizvodjac;
import java.awt.HeadlessException;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import klijentKontroler.KlijentKontroler;

/**
 *
 * @author Milena
 */
public class FProizvodi extends javax.swing.JDialog {

    Proizvod proizvod;
    String naziv;
    String boja;
    String cenaString;
    double cena = 0;

    public FProizvodi(java.awt.Frame parent, boolean modal, Proizvod proizvod) {

        super(parent, modal);
        initComponents();
        popuniCBProizvodjac();
        popuniCBTipovi();
        jTProizvodID.setVisible(false);
        jLProizvodID.setVisible(false);
        jBIzmeni.setVisible(false);
        jBObrisi.setVisible(false);
        this.proizvod = proizvod;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLTipProizvoda = new javax.swing.JLabel();
        jLProizvodjac = new javax.swing.JLabel();
        jCBProizvodjac = new javax.swing.JComboBox<>();
        jCBTipoviProizvoda = new javax.swing.JComboBox<>();
        jLBoja = new javax.swing.JLabel();
        jTBoja = new javax.swing.JTextField();
        jTCena = new javax.swing.JTextField();
        jLCena = new javax.swing.JLabel();
        jLNazivProizvoda = new javax.swing.JLabel();
        jTNazivProizvoda = new javax.swing.JTextField();
        jLProizvodID = new javax.swing.JLabel();
        jTProizvodID = new javax.swing.JTextField();
        jlNazivError = new javax.swing.JLabel();
        jlBojaError = new javax.swing.JLabel();
        jlCenaError = new javax.swing.JLabel();
        jBIzmeni = new javax.swing.JButton();
        jBObrisi = new javax.swing.JButton();
        jBSacuvaj = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Dodavanje novih proizvoda");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Proizvod"));

        jLTipProizvoda.setText("Tip proizvoda");

        jLProizvodjac.setText("Proizvodjac");

        jCBProizvodjac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBProizvodjacActionPerformed(evt);
            }
        });

        jLBoja.setText("Boja");

        jTCena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTCenaActionPerformed(evt);
            }
        });

        jLCena.setText("Cena");

        jLNazivProizvoda.setText("Naziv proizvoda");

        jTNazivProizvoda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTNazivProizvodaActionPerformed(evt);
            }
        });

        jLProizvodID.setText("Proizvod ID");

        jTProizvodID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTProizvodIDActionPerformed(evt);
            }
        });

        jlNazivError.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlNazivError.setForeground(new java.awt.Color(255, 0, 0));

        jlBojaError.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlBojaError.setForeground(new java.awt.Color(255, 0, 0));

        jlCenaError.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlCenaError.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLProizvodID, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLNazivProizvoda, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLBoja, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(77, 77, 77)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTCena, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTProizvodID, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTBoja, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTNazivProizvoda, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlCenaError, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlNazivError, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlBojaError, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLProizvodjac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLCena, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLTipProizvoda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(93, 93, 93)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCBProizvodjac, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCBTipoviProizvoda, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(284, 284, 284))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLProizvodID)
                            .addComponent(jTProizvodID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLNazivProizvoda)
                            .addComponent(jlNazivError, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTNazivProizvoda, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLCena, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTCena, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jlCenaError, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlBojaError, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTBoja, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLBoja, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLTipProizvoda, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCBTipoviProizvoda, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLProizvodjac)
                    .addComponent(jCBProizvodjac, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(493, 493, 493))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 610, 310));

        jBIzmeni.setText("Izmeni ");
        jBIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBIzmeniActionPerformed(evt);
            }
        });
        getContentPane().add(jBIzmeni, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 350, 140, 31));

        jBObrisi.setText("Obriši");
        jBObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBObrisiActionPerformed(evt);
            }
        });
        getContentPane().add(jBObrisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 350, 150, 31));

        jBSacuvaj.setText("Sačuvaj ");
        jBSacuvaj.setMaximumSize(new java.awt.Dimension(80, 30));
        jBSacuvaj.setMinimumSize(new java.awt.Dimension(80, 30));
        jBSacuvaj.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                jBSacuvajComponentRemoved(evt);
            }
        });
        jBSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSacuvajActionPerformed(evt);
            }
        });
        getContentPane().add(jBSacuvaj, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 120, 32));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSacuvajActionPerformed

        naziv = jTNazivProizvoda.getText();
        cenaString = jTCena.getText().trim();
        boja = jTBoja.getText();
        String tip = jCBTipoviProizvoda.getSelectedItem().toString();
        Proizvodjac proizvodjacCB = (Proizvodjac) jCBProizvodjac.getSelectedItem();

        if (izvrsiValidaciju()) {
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog(this, "Da li ste sigurni da želite da sačuvate proizvod?", "Dodavanje proizvoda", dialogButton);
            if (dialogResult == 0) {
                proizvod = new Proizvod(0, naziv, cena, boja, tip, proizvodjacCB);
                try {
                    KlijentKontroler.getInstance().sacuvajProizvod(proizvod);
                    FPretragaNaocara fp = (FPretragaNaocara) getParent();
                    modelTabele.ModelTabeleProizvod model = fp.vratiModel();
                    model.dodajProizvod(proizvod);

                    JOptionPane.showMessageDialog(rootPane, "Uspešno ste dodali novi proizvod!");
                    this.dispose();
                } catch (HeadlessException | IOException ex) {
                    Logger.getLogger(FProizvodi.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(rootPane, "Niste uspesno sacuvali proizvod!", "Greska", JOptionPane.ERROR_MESSAGE);
                }
                System.out.println("Da");
            } else {
                System.out.println("Ne");
                JOptionPane.showMessageDialog(rootPane, "Niste uspesno sacuvali proizvod!", "Greska", JOptionPane.ERROR_MESSAGE);
            }
        }

    }//GEN-LAST:event_jBSacuvajActionPerformed

    private void jCBProizvodjacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBProizvodjacActionPerformed

    }//GEN-LAST:event_jCBProizvodjacActionPerformed

    private void jTNazivProizvodaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTNazivProizvodaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTNazivProizvodaActionPerformed

    private void jBIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBIzmeniActionPerformed

        naziv = jTNazivProizvoda.getText();
        cenaString = jTCena.getText().trim();
        boja = jTBoja.getText();
        String tip = jCBTipoviProizvoda.getSelectedItem().toString();
        Proizvodjac proizvodjacCB = (Proizvodjac) jCBProizvodjac.getSelectedItem();

        if (izvrsiValidaciju()) {
            int id = 0;
            String proizvodId = jTProizvodID.getText();
            try {
                id = Integer.parseInt(proizvodId);
            } catch (NumberFormatException ex) {
            }

            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog(this, "Da li ste sigurni da želite da izmenite proizvod?", "Izmena proizvoda", dialogButton);
            if (dialogResult == 0) {

                proizvod.setNazivProizvoda(naziv);
                proizvod.setCena(cena);
                proizvod.setBoja(boja);
                proizvod.setTip(tip);
                proizvod.setProizvodjac(proizvodjacCB);

                try {
                    KlijentKontroler.getInstance().izmeniProizvod(proizvod);
                    FPretragaNaocara fp = (FPretragaNaocara) getParent();
                    fp.vratiModel().fireTableDataChanged();

                    JOptionPane.showMessageDialog(rootPane, "Uspešno ste izmenili proizvod!");
                    this.dispose();

                    System.out.println("Da");
                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(rootPane, "Niste uspesno izmenili proizvod!", "Greska", JOptionPane.ERROR_MESSAGE);
                    Logger.getLogger(FProizvodi.class.getName()).log(Level.SEVERE, null, ex);
                }

            } else {
                System.out.println("Ne");
                JOptionPane.showMessageDialog(rootPane, "Niste uspesno izmenili proizvod!", "Greska", JOptionPane.ERROR_MESSAGE);
            }

        }
    }//GEN-LAST:event_jBIzmeniActionPerformed

    private void jTProizvodIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTProizvodIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTProizvodIDActionPerformed

    private void jBSacuvajComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jBSacuvajComponentRemoved
        // TODO add your handling code here:

    }//GEN-LAST:event_jBSacuvajComponentRemoved

    private void jBObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBObrisiActionPerformed

        String idProizvoda = jTProizvodID.getText();
        int id = Integer.parseInt(idProizvoda);

        proizvod = new Proizvod(id);
        try {
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog(this, "Da li ste sigurni da želite da izbrišete  proizvod?", "Brisanje proizvoda", dialogButton);

            if (dialogResult == 0) {
                KlijentKontroler.getInstance().obrisiProizvod(proizvod);
                FPretragaNaocara fp1 = (FPretragaNaocara) getParent();
                modelTabele.ModelTabeleProizvod model1 = fp1.vratiModel();
                model1.obrisiProizvod(proizvod);
                fp1.popuniTabeluProizvod();
                System.out.println("Da");
                JOptionPane.showMessageDialog(rootPane, "Uspešno ste izbrisali proizvod!");
                this.dispose();
            } else {
                System.out.println("Ne");
                JOptionPane.showMessageDialog(rootPane, "Niste uspesno izbrisali proizvod!", "Greska", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_jBObrisiActionPerformed

    private void jTCenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTCenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTCenaActionPerformed

    private void popuniCBProizvodjac() {
        jCBProizvodjac.removeAllItems();
        List<Proizvodjac> proizvodjaci = KlijentKontroler.getInstance().vratiSveProizvodjace();
        for (Proizvodjac proizvodjac : proizvodjaci) {
            jCBProizvodjac.addItem(proizvodjac);
        }
    }

    private void popuniCBTipovi() {
        jCBTipoviProizvoda.removeAllItems();
        String[] tipovi = KlijentKontroler.vratiTipove();
        for (String tip : tipovi) {
            jCBTipoviProizvoda.addItem(tip);
        }

    }

    void updateProizvod(Proizvod proizvod) {

        int proizvodId = proizvod.getProizvodId();
        jTProizvodID.setText(String.valueOf(new Integer(proizvodId)));
        jTNazivProizvoda.setText(proizvod.getNazivProizvoda());
        // KAKO UBACITI DOUBLE U TEKSTUALNO POLJE !!!!!!!!!!!!!
        double cena = proizvod.getCena();
        jTCena.setText(String.valueOf(new Double(cena)));

        jTBoja.setText(proizvod.getBoja());
        jCBProizvodjac.setSelectedItem(proizvod.getProizvodjac());
        jCBTipoviProizvoda.setSelectedItem(proizvod.getTip());

        jBSacuvaj.setVisible(false);
        jBIzmeni.setVisible(true);
        jBObrisi.setVisible(true);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBIzmeni;
    private javax.swing.JButton jBObrisi;
    private javax.swing.JButton jBSacuvaj;
    private javax.swing.JComboBox<Object> jCBProizvodjac;
    private javax.swing.JComboBox<String> jCBTipoviProizvoda;
    private javax.swing.JLabel jLBoja;
    private javax.swing.JLabel jLCena;
    private javax.swing.JLabel jLNazivProizvoda;
    private javax.swing.JLabel jLProizvodID;
    private javax.swing.JLabel jLProizvodjac;
    private javax.swing.JLabel jLTipProizvoda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTBoja;
    private javax.swing.JTextField jTCena;
    private javax.swing.JTextField jTNazivProizvoda;
    private javax.swing.JTextField jTProizvodID;
    private javax.swing.JLabel jlBojaError;
    private javax.swing.JLabel jlCenaError;
    private javax.swing.JLabel jlNazivError;
    // End of variables declaration//GEN-END:variables
         private boolean izvrsiValidaciju() {

        if (naziv.isEmpty() || cenaString.isEmpty() || boja.isEmpty()) {
            jlNazivError.setText("Naziv da bude unet!");
            jlBojaError.setText("Boja mora da bude uneta!");
            jlCenaError.setText("Cena mora da bude uneta!");
            return false;
        }

        if (naziv.length() < 3) {
            jlNazivError.setText("Naziv mora da ima najmanje 3 slova!");
            return false;
        }
        if (naziv == null) {
            jlNazivError.setText("Naziv da bude unet!");
            return false;
        }

        try {
//            for (int i = 0; i < cenaString.length(); i++) {
//                if (!Character.isDigit(i)) {
//                    jlCenaError.setText("Cena mora da bude broj!");
//                    break;
//                }
//
//            }
            cena = Double.valueOf(cenaString);

        } catch (NumberFormatException ex) {
            jlCenaError.setText("Cena mora da bude broj!");
            return false;
        }

        if (boja.length() < 3) {
            jlBojaError.setText("Boja mora da ima najmanje 3 slova!");
            return false;
        }
        if (boja == null) {
            jlBojaError.setText("Boja mora da bude uneta!");
            return false;
        }

        return true;
    }
}
