/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Proizvod;
import domen.Proizvodjac;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import klijentKontroler.KlijentKontroler;

/**
 *
 * @author Milena
 */
public class FProizvodi extends javax.swing.JDialog {

    Proizvod proizvod;
    String naziv;
    String boja;
    String cenaString;
    double cena = 0;

    public FProizvodi(java.awt.Frame parent, boolean modal) {

        super(parent, modal);
        initComponents();
        popuniCBProizvodjac();
        popuniCBTipovi();
        jTProizvodID.setVisible(false);
        jLProizvodID.setVisible(false);
        jBIzmeni.setVisible(false);
        jBObrisi.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLTipProizvoda = new javax.swing.JLabel();
        jBSacuvaj = new javax.swing.JButton();
        jLProizvodjac = new javax.swing.JLabel();
        jCBProizvodjac = new javax.swing.JComboBox<>();
        jCBTipoviProizvoda = new javax.swing.JComboBox<>();
        jLNazivError = new javax.swing.JLabel();
        jLCenaError = new javax.swing.JLabel();
        jLBojaError = new javax.swing.JLabel();
        jLNazivProizvoda = new javax.swing.JLabel();
        jLCena = new javax.swing.JLabel();
        jLBoja = new javax.swing.JLabel();
        jTNazivProizvoda = new javax.swing.JTextField();
        jTCena = new javax.swing.JTextField();
        jTBoja = new javax.swing.JTextField();
        jLErrorProizvod = new javax.swing.JLabel();
        jLErrorCena = new javax.swing.JLabel();
        jLErrorBoja = new javax.swing.JLabel();
        jBIzmeni = new javax.swing.JButton();
        jLProizvodID = new javax.swing.JLabel();
        jTProizvodID = new javax.swing.JTextField();
        jBObrisi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Dodavanje novih proizvoda");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLTipProizvoda.setText("Tip proizvoda");
        getContentPane().add(jLTipProizvoda, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 340, 129, 23));

        jBSacuvaj.setText("Sačuvaj ");
        jBSacuvaj.setMaximumSize(new java.awt.Dimension(80, 30));
        jBSacuvaj.setMinimumSize(new java.awt.Dimension(80, 30));
        jBSacuvaj.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                jBSacuvajComponentRemoved(evt);
            }
        });
        jBSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSacuvajActionPerformed(evt);
            }
        });
        getContentPane().add(jBSacuvaj, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 469, 165, 73));

        jLProizvodjac.setText("Proizvodjac");
        getContentPane().add(jLProizvodjac, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 414, 96, -1));

        jCBProizvodjac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBProizvodjacActionPerformed(evt);
            }
        });
        getContentPane().add(jCBProizvodjac, new org.netbeans.lib.awtextra.AbsoluteConstraints(444, 404, 247, 35));

        getContentPane().add(jCBTipoviProizvoda, new org.netbeans.lib.awtextra.AbsoluteConstraints(444, 335, 247, 33));
        getContentPane().add(jLNazivError, new org.netbeans.lib.awtextra.AbsoluteConstraints(846, 99, 89, 31));
        getContentPane().add(jLCenaError, new org.netbeans.lib.awtextra.AbsoluteConstraints(846, 218, 104, 18));
        getContentPane().add(jLBojaError, new org.netbeans.lib.awtextra.AbsoluteConstraints(876, 236, 89, 12));

        jLNazivProizvoda.setText("Naziv proizvoda");
        getContentPane().add(jLNazivProizvoda, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 58, -1, -1));

        jLCena.setText("Cena");
        getContentPane().add(jLCena, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 159, 78, 31));

        jLBoja.setText("Boja");
        getContentPane().add(jLBoja, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 232, 78, 30));

        jTNazivProizvoda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTNazivProizvodaActionPerformed(evt);
            }
        });
        getContentPane().add(jTNazivProizvoda, new org.netbeans.lib.awtextra.AbsoluteConstraints(442, 51, 249, 30));
        getContentPane().add(jTCena, new org.netbeans.lib.awtextra.AbsoluteConstraints(442, 160, 246, 30));
        getContentPane().add(jTBoja, new org.netbeans.lib.awtextra.AbsoluteConstraints(442, 218, 249, 30));

        jLErrorProizvod.setFont(new java.awt.Font("Dialog", 3, 11)); // NOI18N
        jLErrorProizvod.setForeground(new java.awt.Color(204, 0, 0));
        getContentPane().add(jLErrorProizvod, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 87, 345, 30));

        jLErrorCena.setFont(new java.awt.Font("Dialog", 3, 11)); // NOI18N
        jLErrorCena.setForeground(new java.awt.Color(204, 0, 0));
        getContentPane().add(jLErrorCena, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 191, 335, 35));

        jLErrorBoja.setFont(new java.awt.Font("Dialog", 3, 11)); // NOI18N
        jLErrorBoja.setForeground(new java.awt.Color(204, 0, 0));
        getContentPane().add(jLErrorBoja, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 268, 211, 38));

        jBIzmeni.setText("Izmeni ");
        jBIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBIzmeniActionPerformed(evt);
            }
        });
        getContentPane().add(jBIzmeni, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 469, 177, 73));

        jLProizvodID.setText("Proizvod ID");
        getContentPane().add(jLProizvodID, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 8, 101, 25));

        jTProizvodID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTProizvodIDActionPerformed(evt);
            }
        });
        getContentPane().add(jTProizvodID, new org.netbeans.lib.awtextra.AbsoluteConstraints(442, 0, 249, 33));

        jBObrisi.setText("Obriši");
        jBObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBObrisiActionPerformed(evt);
            }
        });
        getContentPane().add(jBObrisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(499, 470, 196, 72));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSacuvajActionPerformed

        naziv = jTNazivProizvoda.getText();
        cenaString = jTCena.getText();
        boja = jTBoja.getText();
        String tip = jCBTipoviProizvoda.getSelectedItem().toString();
        Proizvodjac proizvodjacCB = (Proizvodjac) jCBProizvodjac.getSelectedItem();

        if (izvrsiValidaciju()) {
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog(this, "Da li ste sigurni da želite da sačuvate proizvod?", "Dodavanje proizvoda", dialogButton);
            if (dialogResult == 0) {
                proizvod = new Proizvod(0, naziv, cena, boja, tip, proizvodjacCB);
                try {
                    KlijentKontroler.getInstance().sacuvajProizvod(proizvod);
                    FPretragaNaocara fp = (FPretragaNaocara) getParent();
                    modelTabele.ModelTabeleProizvod model = fp.vratiModel();
                    model.dodajProizvod(proizvod);

                    JOptionPane.showMessageDialog(rootPane, "Uspešno ste dodali novi proizvod!");
                } catch (IOException ex) {
                    Logger.getLogger(FProizvodi.class.getName()).log(Level.SEVERE, null, ex);
                } catch (Exception ex) {
                    Logger.getLogger(FProizvodi.class.getName()).log(Level.SEVERE, null, ex);
                }
                System.out.println("Da");
            } else {
                System.out.println("Ne");
            }
        }

    }//GEN-LAST:event_jBSacuvajActionPerformed

    private void jCBProizvodjacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBProizvodjacActionPerformed

    }//GEN-LAST:event_jCBProizvodjacActionPerformed

    private void jTNazivProizvodaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTNazivProizvodaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTNazivProizvodaActionPerformed

    private void jBIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBIzmeniActionPerformed

        naziv = jTNazivProizvoda.getText();
        cenaString = jTCena.getText();
        boja = jTBoja.getText();
        String tip = jCBTipoviProizvoda.getSelectedItem().toString();
        Proizvodjac proizvodjacCB = (Proizvodjac) jCBProizvodjac.getSelectedItem();

        if (izvrsiValidaciju()) {
            int id = 0;
            String proizvodId = jTProizvodID.getText();
            try {
                id = Integer.parseInt(proizvodId);
            } catch (NumberFormatException ex) {
            }
            try {
                int dialogButton = JOptionPane.YES_NO_OPTION;
                int dialogResult = JOptionPane.showConfirmDialog(this, "Da li ste sigurni da želite da izmenite proizvod?", "Izmena proizvoda", dialogButton);
                if (dialogResult == 0) {

                    proizvod = new Proizvod(id, naziv, cena, boja, tip, proizvodjacCB);
                    KlijentKontroler.getInstance().izmeniProizvod(proizvod);

                    FPretragaNaocara fp = (FPretragaNaocara) getParent();
                    modelTabele.ModelTabeleProizvod model = fp.vratiModel();
                    model.izmeniProizvod(proizvod);

                    JOptionPane.showMessageDialog(rootPane, "Uspešno ste izmenili proizvod!");
                    System.out.println("Da");
                } else {
                    System.out.println("Ne");
                }
            } catch (Exception ex) {
            }
        }
    }//GEN-LAST:event_jBIzmeniActionPerformed

    private void jTProizvodIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTProizvodIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTProizvodIDActionPerformed

    private void jBSacuvajComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jBSacuvajComponentRemoved
        // TODO add your handling code here:

    }//GEN-LAST:event_jBSacuvajComponentRemoved

    private void jBObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBObrisiActionPerformed

        String idProizvoda = jTProizvodID.getText();
        int id = Integer.parseInt(idProizvoda);

        proizvod = new Proizvod(id);
        try {

            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog(this, "Da li ste sigurni da želite da izbrišete  proizvod?", "Brisanje proizvoda", dialogButton);
            if (dialogResult == 0) {
                KlijentKontroler.getInstance().obrisiProizvod(proizvod);
                FPretragaNaocara fp = (FPretragaNaocara) getParent();

                modelTabele.ModelTabeleProizvod model = fp.vratiModel();
                model.obrisiProizvod(proizvod);
                System.out.println("Da");
                JOptionPane.showMessageDialog(rootPane, "Uspešno ste izbrisali proizvod!");
            } else {
                System.out.println("Ne");
                JOptionPane.showMessageDialog(rootPane, "Niste izbrisali proizvod!");
            }
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_jBObrisiActionPerformed

    private void popuniCBProizvodjac() {
        jCBProizvodjac.removeAllItems();
        List<Proizvodjac> proizvodjaci = KlijentKontroler.getInstance().vratiSveProizvodjace();
        for (Proizvodjac proizvodjac : proizvodjaci) {
            jCBProizvodjac.addItem(proizvodjac);
        }
    }

    private void popuniCBTipovi() {
        jCBTipoviProizvoda.removeAllItems();
        String[] tipovi = KlijentKontroler.vratiTipove();
        for (String tip : tipovi) {
            jCBTipoviProizvoda.addItem(tip);
        }

    }

    void updateProizvod(Proizvod proizvod) {

        int proizvodId = proizvod.getProizvodId();
        jTProizvodID.setText(String.valueOf(new Integer(proizvodId)));
        jTNazivProizvoda.setText(proizvod.getNazivProizvoda());
        // KAKO UBACITI DOUBLE U TEKSTUALNO POLJE !!!!!!!!!!!!!
        double cena = proizvod.getCena();
        jTCena.setText(String.valueOf(new Double(cena)));

        jTBoja.setText(proizvod.getBoja());
        jCBProizvodjac.setSelectedItem(proizvod.getProizvodjac());
        jCBTipoviProizvoda.setSelectedItem(proizvod.getTip());

        jBSacuvaj.setVisible(false);
        jBIzmeni.setVisible(true);
        jBObrisi.setVisible(true);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBIzmeni;
    private javax.swing.JButton jBObrisi;
    private javax.swing.JButton jBSacuvaj;
    private javax.swing.JComboBox<Object> jCBProizvodjac;
    private javax.swing.JComboBox<String> jCBTipoviProizvoda;
    private javax.swing.JLabel jLBoja;
    private javax.swing.JLabel jLBojaError;
    private javax.swing.JLabel jLCena;
    private javax.swing.JLabel jLCenaError;
    private javax.swing.JLabel jLErrorBoja;
    private javax.swing.JLabel jLErrorCena;
    private javax.swing.JLabel jLErrorProizvod;
    private javax.swing.JLabel jLNazivError;
    private javax.swing.JLabel jLNazivProizvoda;
    private javax.swing.JLabel jLProizvodID;
    private javax.swing.JLabel jLProizvodjac;
    private javax.swing.JLabel jLTipProizvoda;
    private javax.swing.JTextField jTBoja;
    private javax.swing.JTextField jTCena;
    private javax.swing.JTextField jTNazivProizvoda;
    private javax.swing.JTextField jTProizvodID;
    // End of variables declaration//GEN-END:variables
         private boolean izvrsiValidaciju() {

        if (naziv.isEmpty() || cenaString.isEmpty() || boja.isEmpty()) {
            jLErrorProizvod.setText("Naziv da bude unet!");
            jLErrorBoja.setText("Boja mora da bude uneta!");
            jLErrorCena.setText("Cena mora da bude uneta!");
            return false;
        }

        if (naziv.length() < 3) {
            jLErrorProizvod.setText("Naziv mora da ima najmanje 3 slova!");
            return false;
        }
        if (naziv == null) {
            jLErrorProizvod.setText("Naziv da bude unet!");
            return false;
        }

        try {
            cena = Double.parseDouble(cenaString);
            if (cena == 0) {
                jLErrorCena.setText("Cena mora da bude veca od 0!");
                return false;
            }
//                if (cena = "") {
//                    jLErrorCena.setText("Cena mora da bude veca od 0!");
//                    return;
//                }
        } catch (NumberFormatException ex) { // handle your exception

        }

        if (boja.length() < 3) {
            jLBojaError.setText("Boja mora da ima najmanje 3 slova!");
            return false;
        }
        if (boja == null) {
            jLErrorBoja.setText("Boja mora da bude uneta!");
            return false;
        }
        return true;
    }
}
